Dev
IlyaUsmanov/review1 pull request #1
Opened 2020-04-19 18:42 UTC by IlyaUsmanov

2020-04-20 14:28 UTC, onaga1958 commented
- pep8: IlyaUsmanov/main.py:121:1: W391 blank line at end of file
- decode Цезаря падает с ошибкой
- Виженер добавляет пустые строки в конце

2020-04-23 17:55 UTC, onaga1958 commented
Добавьте пожалуйста ivanov-v-v в коллабораторы

2020-05-02 12:51 UTC, ivanov-v-v requested changes
1. Мы не используем однобуквенные переменные (кроме общепринятых контекстов, где они уместны);
2. Мы пишем названия переменных и функций полностью.
3. Названия переменных это существительные, функций — глаголы.
4. Мы не используем глобальные переменные.
5. Каждый вид шифрования полезно вынести в отдельный файл. Эти файлы нужно вынести в отдельную папку в корне репозитория и подтягивать оттуда

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +alph = []
Глобальные переменные это блокирующая ошибка: с ними задача принята не будет.

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +def fill_alph():
1. Название функции не отражает её смысла
2. Нет докстринга

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +def calc_frequency(text):
`from collections import Counter`

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +alph = []
Кроме того, Альф это инопланетянин из фильма.  
Буквы дефицитные? Пишите названия полностью: не `alph`, а `alphabet`

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +    for i in range(1040, 1104):
К магическим константам у нас нулевая терпимость

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +def code_caesar(text, key, flag):
Лучше было написать класс и сделать эту функцию приватной. У неё очень странная сигнатура, такие служебные функции не должны быть в публичной области видимости. Кроме того, название функции это **глагол**. Тут это не так

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +        if text[i] in alph:
Линейная асимптотика поиска. Добейся константной

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +    min_d = 100000000
Магические константы

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +        d = calc_difference(frequency, temp_freq)
Однобуквенные переменные

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +
Напиши 
```
if __name__ == '__main__':
    main()
```
В `main` должны вызываться функции, которые парсят вход и формируют выход. Это общепринятый формат

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +parser.add_argument('mode')
Нужны комментарии к каждому аргументы и к самому парсеру (help="...")

2020-05-02 12:51 UTC, ivanov-v-v commented on main.py
> +    for i in sys.stdin:
`i` как имя допустимо только тогда, когда это числовой индекс в цикле

2020-05-17 19:30 UTC, ivanov-v-v commented
Напиши нормальный `readme.md`:
1. Там должен быть описан весь функционал (какие шифры поддерживаются, какие бонусы реализованы);
2. Все строчки с кодом должны быть `подсвечены` при помощи \` \`;
3. Должны быть заголовки и подзаголовки в markdown.

2020-05-20 11:47 UTC, ivanov-v-v commented
Ping. Времени на доработки осталось мало, есть шанс схлопотать незач

2020-09-16 07:50 UTC, onaga1958 commented
напоминаю, что команда `pycodestyle . --max-line-length=120 -r` не должна ничего выводить, сейчас вывод такой:
```
IlyaUsmanov/tools.py:4:1: E302 expected 2 blank lines, found 1
IlyaUsmanov/tools.py:13:5: E301 expected 1 blank line, found 0
```

2020-09-19 20:20 UTC, onaga1958 commented on caesar.py
> +    def __do(text, key, flag):
1. Давайте более понятное название, чтобы по нему можно было понять, что этот метод делает
2. Первым аргументом метода должен быть self - экземпляр класса, у которого будет вызываться этот метод. Если хочется вызывать метод непосредственно от класса - нужно использовать декоратор `@classmethod` (в этом случае первый аргумент - cls). Если хочется добавить функцию, которой не нужен класс и не нужен экземпляр, но она связана с классом по смыслу - используйте декторатор `@staticmethod`. В данной реализации у вас __do можно сделать staticmethod'ом, а decode, encode и hack - classmethod'ами. Они должны принимать cls первым аргументом и вызывать __do от него.

2020-09-19 20:20 UTC, onaga1958 commented on caesar.py
> +        alphabet = tools.Alphabet.alphabet
1. `from tools import Alphabet`
2. Зачем лишние переменные создавать? Можно обращаться просто к Alphabet.alphabet

2020-09-19 20:20 UTC, onaga1958 commented on caesar.py
> +                newtext += letter
большое число строк гораздо быстрее складывать через join

2020-09-19 20:20 UTC, onaga1958 commented on caesar.py
> +            temp_freq = tools.calc_frequency(newtext)
частоту незачем пересчитывать для каждого сдвига

2020-09-19 20:20 UTC, onaga1958 commented on main.py
> +            text += line
text = sys.stdin.read()

2020-09-19 20:20 UTC, onaga1958 commented on main.py
> +            result = eval(function + '(text, args.key)')
давайте без eval сделаем, тут это явно лишнее

2020-09-19 20:20 UTC, onaga1958 commented on tools.py
> +    alphabet = get_alphabet.__func__()
можно же просто сложить их...
`alphabet = string.ascii_letters + string.punctuation`

2020-09-19 20:20 UTC, onaga1958 commented on tools.py
> +        return alphabet_dict
используйте dict comprehension, enumerate и уже построенный alphabet:
`alphabet_dict = {... for ... enumerate(alphabet)}`

2020-09-19 20:20 UTC, onaga1958 commented on tools.py
> +        frequency[letter] = counter[letter] / amount
dict comprehension

2020-09-19 20:20 UTC, onaga1958 commented on vigenere.py
> +    def __do(text, key, flag):
аналогичные Цезарю замечания:
1. вместо __do нужно норм название
2. staticmethod'ы и classmethod'ы
3. Большое число строк нужно складывать через join

2020-09-19 20:20 UTC, onaga1958 commented on main.py
> +        with open(args.input_file, 'r', encoding='utf-8') as f:
долой однобуквенные переменные!

2020-09-19 20:20 UTC, onaga1958 commented on vigenere.py
> +        for i in range(len(text)):
1. опять однобуквенная переменная
2. используйте enumerate: `for index, char in enumerate(text):`

2020-09-20 13:19 UTC, onaga1958 commented on caesar.py
> +        return Caesar.__do_encode_or_decode(text, key, -1)
смысл classmethod'a как раз в том, чтобы вызывать методы не от Caesar, а от cls. Тогда если сделать наследника Caesar, класс OctavianAugustus, то у него не придется переопределять decode и encode, а только __do_encode_or_decode

2020-09-20 13:19 UTC, onaga1958 commented on main.py
> +                result = Vigenere.decode(text, args.key)
копипаст, можно определить шифр до выбора режима и записать класс выбранного шифра в переменную

2020-09-20 13:19 UTC, onaga1958 commented on main.py
> +    parser.add_argument('mode', help='one of four modes: encode/decode/frequency/hack')
вместо перечисления в help'e лучше добавить choices. Тогда программа при введении пользователем неправильного mode упадет с максимально понятной ошибкой
`parser.add_argument('mode', choices=['encode', 'decode', 'frequency', 'hack'])`

2020-09-20 13:19 UTC, onaga1958 commented on tools.py
> +    alphabet = get_alphabet.__func__()
зачем нужна эта конструкция? Почему не просто `alphabet = string.ascii_letters + string.punctuation`?

2020-09-20 13:19 UTC, onaga1958 commented on caesar.py
> +                ind = (Alphabet.alphabet_dict[letter] + flag * key) % len(Alphabet.alphabet)
а это случаем не shift_letter?

2020-09-20 13:19 UTC, onaga1958 commented on vigenere.py
> +        return Vigenere.__do_encode_or_decode(text, key, -1)
аналогично Цезарю, `cls.__do_encode_or_decode`

2020-09-22 07:38 UTC, merged

2020-09-22 07:38 UTC, onaga1958 commented
принято